version: "3.9"
services:
    shopping-cart:
        build: .
        command: npm run dev
        hostname: shopping-cart
        ports:
            - "3000:3000"
        volumes:
          - ./src:/usr/app/src
          - ./nodemon.json:/usr/app/nodemon.json
